name: lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install uv
      run: pip install uv
    - name: Run ruff
      run: uv run ruff check src
    - name: Run ruff format check
      run: uv run ruff format --check --diff src
    - name: Run mypy
      run: uv run mypy src/cratere

