name: pytest
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install pipx 
      run: pip install pipx
    - name: Install uv
      run: pipx install uv
    - name: Run pytest 
      run: uv run pytest -v tests

